export default ({ 

    data:[
      { 
        id: 1,
        title:'Роберт Сапольски | О близости людей и других приматов',
        chanel: 'Vert Dider',
        views: '10 тыс.',
        date: '1 неделю',
        thumbnail: require('../assets/f1.jpg'),     
        pathImg: require('../assets/a1.jpg'),
        home:true,
        library: true,
        trend:true,
        subscribe:true,
        history:true,
        likes:true,
        postponed:true,
      },
      {
        id: 2,
        title:' Почему у зебр не бывает язв.',
        chanel: 'Vert Dider',
        views: '10 тыс.',
        date: '1 неделю назад',
        thumbnail: require('../assets/f1.jpg'), 
        pathImg: require('../assets/a2.jpg'),
        home:true,
        library: false,
        trend:true,
        subscribe:true,
        history:true,
        likes:false,
        postponed:true,
      },
      {
        id: 3,
        title:'Инсульт, сердечные приступы и смерть от колдовства.',
        chanel: 'Vert Dider',
        views: '10 тыс.',
        date: '1 неделю назад',
        thumbnail: require('../assets/f1.jpg'), 
        pathImg: require('../assets/a6.jpg'),
        home:true,
        library: true,
        trend:false,
        subscribe:true,
        history:true,
        likes:true,
        postponed:false,
      },
      {
        id: 4,
        title:'Язва, гонка в саванне и горячий шоколад',
        chanel: 'Vert Dider',
        views: '10 тыс.',
        date: '1 неделю назад',
        thumbnail: require('../assets/f1.jpg'), 
        pathImg: require('../assets/a7.jpg'),
        home:true,
        library: true,
        trend:true,
        subscribe:false,
        history:true,
        likes:true,
        postponed:true,
      },
      {
        id: 5,
        title:'Психологический стресс и стрессовая реакция',
        chanel: 'Vert Dider',
        views: '10 тыс.',
        date: '1 неделю назад',
        thumbnail: require('../assets/f1.jpg'), 
        pathImg: require('../assets/a5.jpg'),
        home:true,
        library: true,
        trend:true,
        subscribe:false,
        history:true,
        likes:true,
        postponed:true,
      },
      {
        id: 6,
        title:'Железы, гусиная кожа и гормоны',
        chanel: 'Vert Dider',
        views: '10 тыс.',
        date: '1 неделю назад',
        thumbnail: require('../assets/f1.jpg'), 
        pathImg: require('../assets/a3.jpg'),
        home:true,
        library: true,
        trend:true,
        subscribe:false,
        history:true,
        likes:true,
        postponed:true,
      },
      {
        id: 7,
        title:'Стресс, метаболизм и ликвидация активов',
        chanel: 'Vert Dider',
        views: '10 тыс.',
        date: '1 неделю назад',
        thumbnail: require('../assets/f1.jpg'), 
        pathImg: require('../assets/a4.jpg'),
        home:true,
        library: true,
        trend:true,
        subscribe:false,
        history:true,
        likes:true,
        postponed:true,
      },
      {
        id: 8,
        title:'Наркоманы, адреналиновые наркоманы и удовольствие',
        chanel: 'Vert Dider',
        views: '10 тыс.',
        date: '1 неделю назад',
        thumbnail: require('../assets/f1.jpg'), 
        pathImg: require('../assets/a8.jpg'),
        home:true,
        library: true,
        trend:true,
        subscribe:false,
        history:true,
        likes:true,
        postponed:true,
      },
      
    ]
})